name: weather_app
description: Flutter Weather App with Firebase Authentication
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3

flutter:
  uses-material-design: true
